/**
 * Filelist: rtl.f
 */
+incdir+${MOR1KX}/mor1kx/rtl/verilog
${MOR1KX}/mor1kx/rtl/verilog/mor1kx.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_branch_prediction.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_bus_if_avalon.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_bus_if_wb32.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_cache_lru.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_cfgrs.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_cpu.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_cpu_cappuccino.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_cpu_espresso.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_cpu_prontoespresso.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_ctrl_cappuccino.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_ctrl_espresso.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_ctrl_prontoespresso.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_dcache.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_decode.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_decode_execute_cappuccino.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_dmmu.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_execute_alu.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_fetch_cappuccino.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_fetch_espresso.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_fetch_prontoespresso.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_fetch_tcm_prontoespresso.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_icache.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_immu.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_lsu_cappuccino.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_lsu_espresso.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_pic.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_rf_cappuccino.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_rf_espresso.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_simple_dpram_sclk.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_store_buffer.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_ticktimer.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_true_dpram_sclk.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_wb_mux_cappuccino.v
${MOR1KX}/mor1kx/rtl/verilog/mor1kx_wb_mux_espresso.v
${MOR1KX}/mor1kx/rtl/verilog/pfpu32/pfpu32_addsub.v
${MOR1KX}/mor1kx/rtl/verilog/pfpu32/pfpu32_cmp.v
${MOR1KX}/mor1kx/rtl/verilog/pfpu32/pfpu32_f2i.v
${MOR1KX}/mor1kx/rtl/verilog/pfpu32/pfpu32_i2f.v
${MOR1KX}/mor1kx/rtl/verilog/pfpu32/pfpu32_muldiv.v
${MOR1KX}/mor1kx/rtl/verilog/pfpu32/pfpu32_rnd.v
${MOR1KX}/mor1kx/rtl/verilog/pfpu32/pfpu32_top.v

${MOR1KX}/rtl/mor1kx_w.sv


